### ISSUE TITLE
Support Mac OS ?

### ISSUE THREAD

**Issue by MrTomek** [imLinguin/plan-lekcji#4]
Macie w planie wspierać Mac Os  / iOS / Androida ?

**Comment by imLinguin** [comment]
Postaramy się w najbliższym czasie ogarnąć coś w kierunku macOS. Jeśli chodzi o smartfony (android, iOS) póki co nie mamy takich planów.

**Comment by olek-arsee** [comment]
Tak jak @imLinguin pisał, wersja na macOS będzie na dniach. Jeśli chodzi o wersję na iOS / Android to moglibyśmy zrobić ją na szybko jako PWA, ale jak już to wolelibyśmy oddać wersję natywną w Darcie, albo chociaż w React Native, a z tym nie byłoby prędko.

**Comment by imLinguin** [comment]
Wsparcie MacOS dodane w najnowszym wydaniu. Więcej szczegółów niedługo w README
